name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.secretPass }}
        
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/nicopollano/menud-frontend:latest

    #- name: Trigger Portainer Webhook
    #  if: success()
    #  run: |
    #    curl -k -X POST https://docker.pidrive.com.ar/api/webhooks/f3923f2f-96e7-4e84-a070-4d92adf619fa
